name: build
on:
  push:
    branches:
      - master
  pull_request:
permissions: 
  contents: read
  security-events: write
jobs:
  build:
    name: Build
    runs-on: ubuntu-20.04
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
      
      - name: Install dependencies
        run: |
          python3 -m pip install --user pipx
          python3 -m pipx ensurepath
          pip install pyyaml requests
      
      - name: Scan playbook for CVEs
        run: |
      - name: Install dependencies
        run: |
          pip install pyyaml requests

      - name: Scan playbooks for CVEs
        run: |
          python3 <<EOF
          import yaml
          import requests
          import glob
          import os
          import subprocess
          import sys

          def check_package_manager(manager):
              try:
                  if manager == 'pip':
                      subprocess.run([sys.executable, '-m', 'pip', '--version'], check=True)
                  else:
                      subprocess.run([manager, '--version'], check=True)
                  print(f"{manager} is installed")
                  return True
              except subprocess.CalledProcessError:
                  print(f"{manager} is not installed")
                  return False
              except FileNotFoundError:
                  print(f"{manager} is not found")
                  return False

          def scan_playbook(file_path):
              print(f"\nAttempting to scan {file_path}")
              try:
                  with open(file_path, 'r') as file:
                      playbook = yaml.safe_load(file)
                  
                  print(f"Successfully loaded {file_path}")
                  versions = []
                  for play in playbook:
                      if isinstance(play, dict) and 'tasks' in play:
                          for task in play['tasks']:
                              if isinstance(task, dict):
                                  for manager in ['apt', 'win_chocolatey', 'winget', 'pip', 'npm']:
                                      if manager in task:
                                          package = task[manager].get('name', '')
                                          if package:
                                              versions.append(package)
                                              print(f"Found {manager} package: {package}")
                  
                  if not versions:
                      print(f"No packages found in {file_path}")
                  
                  for version in versions:
                      print(f"Checking {version} for vulnerabilities...")
                      response = requests.get(f'https://services.nvd.nist.gov/rest/json/cves/1.0?keyword={version}')
                      if response.json()['totalResults'] > 0:
                          print(f"  WARNING: Potential vulnerability found for {version}")
                      else:
                          print(f"  No known vulnerabilities found for {version}")
              except Exception as e:
                  print(f"Error processing {file_path}: {str(e)}")

          print("Script started")
          print(f"Current working directory: {os.getcwd()}")

          package_managers = ['apt', 'winget', 'chocolatey', 'pip', 'npm']
          for manager in package_managers:
              check_package_manager(manager)

          playbook_files = glob.glob('*.yml')
          print(f"Found {len(playbook_files)} playbook files")

          if not playbook_files:
              print("No playbook files found in the playbooks directory.")
          else:
              for playbook_file in playbook_files:
                  scan_playbook(playbook_file)

          print("Script finished")
          EOF


      # 1. Scanner de vulnérabilités avec Trivy
      - name: Run Trivy vulnerability scanner in FS mode - table logs
        continue-on-error: true
        uses: aquasecurity/trivy-action@0.28.0
        with:
          scan-type: 'fs'
          scan-ref: '.'
          hide-progress: false
          format: 'table'
          exit-code: '1'
          severity: 'CRITICAL,HIGH,MEDIUM,LOW'

      - name: Run Trivy vulnerability scanner in FS mode - sarif mode
        continue-on-error: true
        uses: aquasecurity/trivy-action@0.28.0
        with:
          scan-type: 'fs'
          scan-ref: '.'
          hide-progress: false
          format: 'sarif'
          output: 'trivy-results.sarif'
          exit-code: '1'
          severity: 'CRITICAL,HIGH,MEDIUM,LOW'

      - name: Debug SARIF files
        continue-on-error: true
        run: ls -l . && cat trivy-results.sarif || echo "No trivy-results.sarif file"

      - name: Upload Trivy scan results to GitHub Security tab
        uses: github/codeql-action/upload-sarif@v3
        with:
          sarif_file: trivy-results.sarif

          
      # 2. Analyse de sécurité avec Semgrep
      - name: Install Sempgrp
        run: |
          python3 -m pip install --user pipx
          python3 -m pipx ensurepath
          pipx install semgrep
      - name: Run Semgrep
        continue-on-error: true
        run: |
          semgrep scan --verbose --sarif --output semgrep-results.sarif --config auto .
  
      - name: Debug SARIF files
        continue-on-error: true
        run: ls -l . && cat semgrep-results.sarif || echo "No semgrep-results.sarif file"
        
      - name: Upload Semgrep SARIF Results
        uses: github/codeql-action/upload-sarif@v3
        with:
          sarif_file: semgrep-results.sarif

      # 3. Analyse de qualité et de bonnes pratiques avec Ansible Lint
      - name: Install Ansible Lint
        run: sudo apt-get update && sudo apt-get install -y ansible-lint
      - name: Run Ansible Lint
        continue-on-error: true
        run: ansible-lint .

      # 4. Analyse avec Checkov
      - name: Run Checkov scan
        continue-on-error: true
        uses: bridgecrewio/checkov-action@master
        with:
          directory: .
          framework: ansible
          output_format: sarif
          output_file_path: checkov-results

      - name: Debug SARIF files
        continue-on-error: true
        run: ls -l . && cat checkov-results/results_sarif.sarif || echo "No checkov-results/results_sarif.sarif file" 

      # Upload des résultats dans GitHub Security
      - name: Upload Checkov SARIF Results
        uses: github/codeql-action/upload-sarif@v3
        with:
          sarif_file: checkov-results/results_sarif.sarif

      # 5. Analyse avec Checkov
      - name: Run KICS Scan
        continue-on-error: true
        uses: Checkmarx/kics-github-action@v1.7.0
        with:
          path: '.'
          output_formats: sarif
          output_path: kics-results
          platform: ansible
          fail_on: high
          disable_secrets: true
          type: ansible

      - name: Debug SARIF files
        continue-on-error: true
        run: ls -l . && cat kics-results/results.sarif || echo "No kics-results/results.sarif file"
          
      - name: Upload SARIF file
        uses: github/codeql-action/upload-sarif@v3
        with:
          sarif_file: kics-results/results.sarif
