name: build
on:
  push:
    branches:
      - master
  pull_request:
permissions: 
  contents: read
  security-events: write
jobs:
  build:
    name: Build
    runs-on: ubuntu-20.04
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
      
      - name: Install dependencies
        run: |
          python3 -m pip install --user pipx
          python3 -m pipx ensurepath
          pip install pyyaml requests
      
      - name: Scan playbook for CVEs
        run: |
      - name: Install dependencies
        run: |
          pip install pyyaml requests

      - name: Scan playbooks for CVEs
        run: |
          python3 <<EOF
          import yaml
          import requests
          import glob
          import os
          import time

          def check_vulnerability(package, version):
              print(f"Checking {package} version {version} for vulnerabilities...")
              try:
                  response = requests.get(f'https://services.nvd.nist.gov/rest/json/cves/2.0?keywordSearch={package}%20{version}')
                  response.raise_for_status()
                  data = response.json()
                  if data['totalResults'] > 0:
                      print(f"  WARNING: Potential vulnerability found for {package} version {version}")
                      return True
                  else:
                      print(f"  No known vulnerabilities found for {package} version {version}")
                      return False
              except requests.exceptions.RequestException as e:
                  print(f"Error checking vulnerabilities: {e}")
                  return False
              except ValueError:
                  print(f"Error decoding JSON response for {package} version {version}")
                  return False

          def scan_playbook(file_path):
              print(f"\nScanning {file_path}")
              with open(file_path, 'r') as file:
                  playbook = yaml.safe_load(file)
              
              vulnerabilities_found = False
              for play in playbook:
                  if 'tasks' in play:
                      for task in play['tasks']:
                          if isinstance(task, dict):
                              for manager in ['apt', 'winget', 'win_chocolatey', 'npm', 'pip']:
                                  if manager in task:
                                      package = task[manager].get('name', '')
                                      version = task[manager].get('version', '')
                                      if package and version:
                                          if check_vulnerability(package, version):
                                              vulnerabilities_found = True
                                              print(f"Vulnerability found in task: {task.get('name', 'Unnamed task')}")
                                          time.sleep(1)  # Add a 1-second delay between requests
              
              if vulnerabilities_found:
                  print(f"Vulnerabilities found in {file_path}")
              else:
                  print(f"No vulnerabilities found in {file_path}")

          playbook_files = glob.glob('*.yml')
          print(f"Found {len(playbook_files)} playbook files")

          if not playbook_files:
              print("No playbook files found in the playbooks directory.")
          else:
              for playbook_file in playbook_files:
                  scan_playbook(playbook_file)
          EOF


      # 1. Scanner de vulnérabilités avec Trivy
      - name: Run Trivy vulnerability scanner in FS mode - table logs
        continue-on-error: true
        uses: aquasecurity/trivy-action@0.28.0
        with:
          scan-type: 'fs'
          scan-ref: '.'
          hide-progress: false
          format: 'table'
          exit-code: '1'
          severity: 'CRITICAL,HIGH,MEDIUM,LOW'

      - name: Run Trivy vulnerability scanner in FS mode - sarif mode
        continue-on-error: true
        uses: aquasecurity/trivy-action@0.28.0
        with:
          scan-type: 'fs'
          scan-ref: '.'
          hide-progress: false
          format: 'sarif'
          output: 'trivy-results.sarif'
          exit-code: '1'
          severity: 'CRITICAL,HIGH,MEDIUM,LOW'

      - name: Debug SARIF files
        continue-on-error: true
        run: ls -l . && cat trivy-results.sarif || echo "No trivy-results.sarif file"

      - name: Upload Trivy scan results to GitHub Security tab
        uses: github/codeql-action/upload-sarif@v3
        with:
          sarif_file: trivy-results.sarif

          
      # 2. Analyse de sécurité avec Semgrep
      - name: Install Sempgrp
        run: |
          python3 -m pip install --user pipx
          python3 -m pipx ensurepath
          pipx install semgrep
      - name: Run Semgrep
        continue-on-error: true
        run: |
          semgrep scan --verbose --sarif --output semgrep-results.sarif --config auto .
  
      - name: Debug SARIF files
        continue-on-error: true
        run: ls -l . && cat semgrep-results.sarif || echo "No semgrep-results.sarif file"
        
      - name: Upload Semgrep SARIF Results
        uses: github/codeql-action/upload-sarif@v3
        with:
          sarif_file: semgrep-results.sarif

      # 3. Analyse de qualité et de bonnes pratiques avec Ansible Lint
      - name: Install Ansible Lint
        run: sudo apt-get update && sudo apt-get install -y ansible-lint
      - name: Run Ansible Lint
        continue-on-error: true
        run: ansible-lint .

      # 4. Analyse avec Checkov
      - name: Run Checkov scan
        continue-on-error: true
        uses: bridgecrewio/checkov-action@master
        with:
          directory: .
          framework: ansible
          output_format: sarif
          output_file_path: checkov-results

      - name: Debug SARIF files
        continue-on-error: true
        run: ls -l . && cat checkov-results/results_sarif.sarif || echo "No checkov-results/results_sarif.sarif file" 

      # Upload des résultats dans GitHub Security
      - name: Upload Checkov SARIF Results
        uses: github/codeql-action/upload-sarif@v3
        with:
          sarif_file: checkov-results/results_sarif.sarif

      # 5. Analyse avec Checkov
      - name: Run KICS Scan
        continue-on-error: true
        uses: Checkmarx/kics-github-action@v1.7.0
        with:
          path: '.'
          output_formats: sarif
          output_path: kics-results
          platform: ansible
          fail_on: high
          disable_secrets: true
          type: ansible

      - name: Debug SARIF files
        continue-on-error: true
        run: ls -l . && cat kics-results/results.sarif || echo "No kics-results/results.sarif file"
          
      - name: Upload SARIF file
        uses: github/codeql-action/upload-sarif@v3
        with:
          sarif_file: kics-results/results.sarif
